name: smirl_version_checker
description: the package that check if a new version is on playstore or appstore, based on new_version package with exception checker
version: 0.0.3
homepage: https://github.com/francisnnumbi/smirl_version_checker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  device_info_plus: ^3.2.2
  package_info_plus: ^1.4.2
  html: ^0.15.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

